version: '3'
services:
  h2:
    image: buildo/h2database
    ports:
      - 8082:8082

  springbootapp:
    image: seventeenth-exercise:1.0
    network_mode: bridge
    container_name: springbootapp
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - h2
    environment:
      - DB_DRIVER=org.h2.Driver
      - DB_URL=jdbc:h2:tcp://h2:1521/my-db-name
      - DB_USER=sa