
INSERT INTO GENRE (TITLE)VALUES ('genre1');
INSERT INTO GENRE (TITLE)VALUES ('genre2');


INSERT INTO AUTHOR (NAME)VALUES ('author1');
INSERT INTO AUTHOR (NAME)VALUES ('author2');
INSERT INTO AUTHOR (NAME)VALUES ('author3');

INSERT INTO BOOK (TITLE)VALUES ('book1');
INSERT INTO BOOK (TITLE)VALUES ('book2');

INSERT INTO BOOKS_GENRES (BOOK_ID ,GENRE_ID )VALUES (1,1);
INSERT INTO BOOKS_AUTHORS (BOOK_ID , AUTHOR_ID)VALUES (1,1);
INSERT INTO BOOKS_AUTHORS (BOOK_ID , AUTHOR_ID)VALUES (1,2);


