
INSERT INTO GENRE (TITLE)VALUES ('roman');
INSERT INTO GENRE (TITLE)VALUES ('horror');
INSERT INTO GENRE (TITLE)VALUES ('yzhas');
INSERT INTO GENRE (TITLE)VALUES ('detectiv');

INSERT INTO AUTHOR (NAME)VALUES ('PUSHKIN');
INSERT INTO AUTHOR (NAME)VALUES ('MEDVEDEV');
INSERT INTO AUTHOR (NAME)VALUES ('avtor3');
INSERT INTO AUTHOR (NAME)VALUES ('avtor4');

INSERT INTO BOOK (TITLE)VALUES ('book1');
INSERT INTO BOOK (TITLE)VALUES ('book2');
INSERT INTO BOOK (TITLE)VALUES ('book3');
INSERT INTO BOOK (TITLE)VALUES ('book4');

INSERT INTO BOOKS_GENRES (BOOK_ID ,GENRE_ID )VALUES (1,1);
INSERT INTO BOOKS_AUTHORS (BOOK_ID , AUTHOR_ID)VALUES (1,1);
INSERT INTO BOOKS_AUTHORS (BOOK_ID , AUTHOR_ID)VALUES (1,2);


