
DROP TABLE  IF EXISTS BOOK;
DROP TABLE  IF EXISTS AUTHOR;
DROP TABLE  IF EXISTS GENRE;
DROP TABLE  IF EXISTS BOOK_GENRE;
DROP TABLE  IF EXISTS BOOK_AUTHOR;

CREATE TABLE BOOK (ID BIGINT  NOT NULL AUTO_INCREMENT, TITLE VARCHAR(255),PRIMARY KEY (ID));
CREATE TABLE AUTHOR (ID BIGINT  NOT NULL AUTO_INCREMENT, NAME VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE GENRE (ID BIGINT  NOT NULL AUTO_INCREMENT, TITLE VARCHAR(255), PRIMARY KEY (ID));

CREATE TABLE BOOKS_AUTHORS( BOOK_ID  BIGINT NOT NULL, AUTHOR_ID  BIGINT NOT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES  BOOK (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES  AUTHOR (ID) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE  BOOKS_GENRES ( BOOK_ID  BIGINT NOT NULL, GENRE_ID  BIGINT NOT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES  BOOK (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (GENRE_ID) REFERENCES  GENRE (ID) ON DELETE CASCADE ON UPDATE CASCADE);
